In [1]:
import tensorflow as tf
print(tf.__version__)
print(tf.keras.__version__)

2.12.0
2.12.0


In [2]:
if tf.test.is_gpu_available():
    print('Running on GPU')
else:
    print('Running on CPU')

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


Running on GPU


In [3]:
tf.config.list_logical_devices('CPU')

[LogicalDevice(name='/device:CPU:0', device_type='CPU')]

In [4]:
tf.config.list_logical_devices('GPU')

[LogicalDevice(name='/device:GPU:0', device_type='GPU')]

**Tensor Constant**

In [7]:
a=tf.constant(42)
a

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [8]:
a.numpy()

42

In [9]:
a1=tf.constant(1,dtype=tf.int64)
a1

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [12]:
a2=tf.constant([[1,2,3],[2,3,4]])
a2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [2, 3, 4]], dtype=int32)>

In [14]:
a2.numpy()

array([[1, 2, 3],
       [2, 3, 4]], dtype=int32)

In [15]:
print('shape:',a2.shape)
print(a2.dtype)

shape: (2, 3)
<dtype: 'int32'>


**Commonly used method is to generate constant tf.ones and the tf.zeros like of numpy np.ones & np.zeros**

In [17]:
print(tf.ones(shape=(2,2)))

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)


In [18]:
print(tf.zeros(shape=(2,2)))

tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)


In [19]:
import tensorflow as tf

x1=tf.constant([[1,2,3],[4,5,6]])
x2=tf.constant([[6,5,3],[5,6,8]])

result=tf.add(x1,x2)

print(result)

tf.Tensor(
[[ 7  7  6]
 [ 9 11 14]], shape=(2, 3), dtype=int32)


**Random constant**

In [21]:
tf.random.normal(shape=(2,2),mean=0,stddev=1)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 1.6096411 , -0.8717185 ],
       [ 0.4500014 ,  0.44701487]], dtype=float32)>

In [24]:
tf.random.uniform(shape=(2,2),minval=0,maxval=100,dtype=tf.int32)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[21, 83],
       [16, 77]], dtype=int32)>

**Variables**

A variable is a special tensor that is used to store variable values ​​and needs to be initialized with some values

In [27]:
v1=0 #python variable
v2=tf.Variable(42)
v3=tf.Variable([[1,2,3],[4,5,6],[6,2,1]])
v1,v2,v3


(0,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=42>,
 <tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6],
        [6, 2, 1]], dtype=int32)>)

In [28]:
float_var64 = tf.Variable(89, dtype = tf.float64)
float_var64.dtype

tf.float64

`TensorFlow has a large number of built-in datatypes.`

datatype | description
- | -
 tf.float16 | 16-bit half-precision floating-point.
 tf.float32 | 32-bit single-precision floating-point.
 tf.float64 | 64-bit double-precision floating-point.
 tf.bfloat16 | 16-bit truncated floating-point.
 tf.complex64 | 64-bit single-precision complex.
 tf.complex128 | 128-bit double-precision complex.
 tf.int8 | 8-bit signed integer.
 tf.uint8 | 8-bit unsigned integer.
 tf.uint16 | 16-bit unsigned integer.
 tf.uint32 | 32-bit unsigned integer.
 tf.uint64 | 64-bit unsigned integer.
 tf.int16 | 16-bit signed integer.
 tf.int32 | 32-bit signed integer.
 tf.int64 | 64-bit signed integer.
 tf.bool | Boolean.
 tf.string | String.
 tf.qint8 | Quantized 8-bit signed integer.
 tf.quint8 | Quantized 8-bit unsigned integer.
 tf.qint16 | Quantized 16-bit signed integer.
 tf.quint16 | Quantized 16-bit unsigned integer.
 tf.qint32 | Quantized 32-bit signed integer.
 tf.resource | Handle to a mutable resource.
 tf.variant | Values of arbitrary types.


To reassign a variable, use var.assign()

In [29]:
var_reassign = tf.Variable(89.)
var_reassign

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=89.0>

In [31]:
var_reassign.assign(25.)
var_reassign

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=25.0>

In [32]:
initial_value = tf.random.normal(shape=(2,2))
a = tf.Variable(initial_value)
print(a)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-0.7593853 ,  1.4741036 ],
       [ 0.73372257,  0.66496533]], dtype=float32)>


We can assign "=" with assign (value), or assign_add (value) with "+ =", or assign_sub (value) with "-="

In [33]:
new_value = tf.random.normal(shape=(2, 2))
a.assign(new_value)
for i in range(2):
    for j in range(2):
        assert a[i, j] == new_value[i, j]

In [34]:
added_value = tf.random.normal(shape=(2,2))
a.assign_add(added_value)
for i in range(2):
    for j in range(2):
        assert a[i,j] == new_value[i,j]+added_value[i,j]

**Shaping a tensor**

In [36]:
tensor = tf.Variable([ [ [0., 1., 2.], [3., 4., 5.] ], [ [6., 7., 8.], [9., 10., 11.] ] ]) # tensor variable
print(tensor.shape)
print(tensor)

(2, 2, 3)
<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.]],

       [[ 6.,  7.,  8.],
        [ 9., 10., 11.]]], dtype=float32)>


Tensors may be reshaped and retain the same values, as is often required for constructing neural networks.

In [37]:
tensor1 = tf.reshape(tensor,[2,6]) # 2 rows 6 cols
tensor2 = tf.reshape(tensor,[1,12]) # 1 rows 12 cols
tensor1

<tf.Tensor: shape=(2, 6), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.]], dtype=float32)>

In [38]:
tensor2 = tf.reshape(tensor,[1,12]) # 1 row 12 columns
tensor2

<tf.Tensor: shape=(1, 12), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]],
      dtype=float32)>

**Ranking (dimensions) of a tensor**

The rank of a tensor is the number of dimensions it has, that is, the number of indices that are required to specify any particular element of that tensor.

In [39]:
tf.rank(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

(the shape is () because the output here is a scalar value)

**Specifying an element of a tensor**

In [40]:
tensor3 = tensor[1, 0, 2] # slice 1, row 0, column 2
tensor3

<tf.Tensor: shape=(), dtype=float32, numpy=8.0>

In [41]:
tensor4 = tensor[0, 1, 1 ] # slice 1, row 0, column 2
tensor4

<tf.Tensor: shape=(), dtype=float32, numpy=4.0>

**Casting a tensor to a NumPy/Python variable**

In [42]:
print(tensor.numpy())

[[[ 0.  1.  2.]
  [ 3.  4.  5.]]

 [[ 6.  7.  8.]
  [ 9. 10. 11.]]]


In [43]:
print(tensor[1, 0, 2].numpy())

8.0


**Finding the size (number of elements) of a tensor**

In [44]:
tensor_size = tf.size(input=tensor).numpy()
tensor_size

12

In [45]:
#the datatype of a tensor
tensor3.dtype

tf.float32

**Tensorflow mathematical operations**

Can be used as numpy for artificial operations. Tensorflow can not execute these operations on the GPU or TPU

In [46]:
a = tf.random.normal(shape=(2,2))
b = tf.random.normal(shape=(2,2))
c = a+b
d = tf.square(c)
e = tf.exp(c)
print(a)
print(b)
print(c)
print(d)
print(e)

tf.Tensor(
[[ 1.7020539  -1.0913601 ]
 [ 0.78206027 -1.2376848 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-0.5036746   0.74235374]
 [ 0.9833507  -0.48230132]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 1.1983793  -0.34900635]
 [ 1.7654109  -1.7199862 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1.4361129  0.12180544]
 [3.1166756  2.9583526 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[3.3147404  0.70538867]
 [5.843973   0.17906862]], shape=(2, 2), dtype=float32)


In [48]:
print(tensor)

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.]],

       [[ 6.,  7.,  8.],
        [ 9., 10., 11.]]], dtype=float32)>


**Performing element-wise primitive tensor operations**

In [47]:
tensor*tensor

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[  0.,   1.,   4.],
        [  9.,  16.,  25.]],

       [[ 36.,  49.,  64.],
        [ 81., 100., 121.]]], dtype=float32)>

**Broadcasting**

Element-wise tensor operations support broadcasting in the same way that NumPy arrays do.

The simplest example is that of multiplying a tensor by a scalar:

In [49]:
tensor4 = tensor*4
print(tensor4)

tf.Tensor(
[[[ 0.  4.  8.]
  [12. 16. 20.]]

 [[24. 28. 32.]
  [36. 40. 44.]]], shape=(2, 2, 3), dtype=float32)


In [50]:
matrix_u = tf.constant([[3,4,3]])
matrix_v = tf.constant([[1,2,1]])

tf.matmul(matrix_u, tf.transpose(a=matrix_v))

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[14]], dtype=int32)>

**Casting a tensor to another (tensor) datatype**

In [51]:
i = tf.cast(tensor1, dtype=tf.int32)
i

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]], dtype=int32)>

With truncation

In [52]:
j = tf.cast(tf.constant(4.9), dtype=tf.int32)
j

<tf.Tensor: shape=(), dtype=int32, numpy=4>

**Declaring Ragged tensors**

A ragged tensor is a tensor with one or more ragged dimensions. Ragged dimensions are dimensions that have slices that may have different lengths.There are a variety of methods for declaring ragged arrays, the simplest being a constant ragged array.

In [53]:
ragged =tf.ragged.constant([[5, 2, 6, 1], [], [4, 10, 7], [8], [6,7]])

print(ragged)
print(ragged[0,:])
print(ragged[1,:])
print(ragged[2,:])
print(ragged[3,:])
print(ragged[4,:])

<tf.RaggedTensor [[5, 2, 6, 1], [], [4, 10, 7], [8], [6, 7]]>
tf.Tensor([5 2 6 1], shape=(4,), dtype=int32)
tf.Tensor([], shape=(0,), dtype=int32)
tf.Tensor([ 4 10  7], shape=(3,), dtype=int32)
tf.Tensor([8], shape=(1,), dtype=int32)
tf.Tensor([6 7], shape=(2,), dtype=int32)


Finding the squared difference between two tensors

In [54]:
varx = [1,3,5,7,11]
vary = 5
varz = tf.math.squared_difference(varx,vary)
varz

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([16,  4,  0,  4, 36], dtype=int32)>

**Finding the mean**

The following is the signature of tf.reduce_mean().

Note that this is equivalent to np.mean, except that it infers the return datatype from the input tensor, whereas np.mean allows you to specify the output type (defaulting to float64):

tf.reduce_mean(input_tensor, axis=None, keepdims=None, name=None)

In [55]:
#Defining a constant
numbers = tf.constant([[4., 5.], [7., 3.]])

In [56]:
tf.reduce_mean(input_tensor=numbers)
#( 4. + 5. + 7. + 3.)/4 = 4.75

<tf.Tensor: shape=(), dtype=float32, numpy=4.75>

Find the mean across columns (that is, reduce rows) with this:

In [57]:
tf.reduce_mean(input_tensor=numbers, axis=0) # [ (4. + 7. )/2 , (5. + 3.)/2 ] = [5.5, 4.]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([5.5, 4. ], dtype=float32)>

When keepdims is True, the reduced axis is retained with a length of 1

In [58]:
tf.reduce_mean(input_tensor=numbers, axis=0, keepdims=True)

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[5.5, 4. ]], dtype=float32)>

Find the mean across rows (that is, reduce columns) with this:

In [59]:
tf.reduce_mean(input_tensor=numbers, axis=1) # [ (4. + 5. )/2 , (7. + 3. )/2] = [4.5, 5]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([4.5, 5. ], dtype=float32)>

When keepdims is True, the reduced axis is retained with a length of 1:

In [60]:
tf.reduce_mean(input_tensor=numbers, axis=1, keepdims=True)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[4.5],
       [5. ]], dtype=float32)>

**Generating tensors filled with random values**

Using tf.random.normal()
tf.random.normal() outputs a tensor of the given shape filled with values of the dtype type from a normal distribution.

The required signature is as follows:

tf. random.normal(shape, mean = 0, stddev =2, dtype=tf.float32, seed=None, name=None)

In [61]:
tf.random.normal(shape = (3,2), mean=10, stddev=2, dtype=tf.float32, seed=None, name=None)
ran = tf.random.normal(shape = (3,2), mean=10.0, stddev=2.0)
print(ran)

tf.Tensor(
[[ 4.9285784 11.715346 ]
 [10.599101   9.935163 ]
 [ 9.653803   8.495513 ]], shape=(3, 2), dtype=float32)


Using tf.random.uniform()
The required signature is this:

tf.random.uniform(shape, minval = 0, maxval= None, dtype=tf.float32, seed=None, name=None)

In [62]:
tf.random.uniform(shape = (2,4), minval=0, maxval=None, dtype=tf.float32, seed=None, name=None)

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[0.27334988, 0.35345602, 0.6194047 , 0.9910294 ],
       [0.19613492, 0.7286948 , 0.48068154, 0.04687417]], dtype=float32)>

In [63]:
tf.random.set_seed(11)
ran1 = tf.random.uniform(shape = (2,2), maxval=10, dtype = tf.int32)
ran2 = tf.random.uniform(shape = (2,2), maxval=10, dtype = tf.int32)
print(ran1) #Call 1
print(ran2)

tf.Tensor(
[[4 6]
 [5 2]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[9 7]
 [9 4]], shape=(2, 2), dtype=int32)


In [64]:
tf.random.set_seed(11) #same seed
ran1 = tf.random.uniform(shape = (2,2), maxval=10, dtype = tf.int32)
ran2 = tf.random.uniform(shape = (2,2), maxval=10, dtype = tf.int32)
print(ran1) #Call 2
print(ran2)

tf.Tensor(
[[4 6]
 [5 2]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[9 7]
 [9 4]], shape=(2, 2), dtype=int32)


**Practical example of Random values using Dices**

In [65]:
dice1 = tf.Variable(tf.random.uniform([10, 1], minval=1, maxval=7, dtype=tf.int32))
dice2 = tf.Variable(tf.random.uniform([10, 1], minval=1, maxval=7, dtype=tf.int32))
# We may add dice1 and dice2 since they share the same shape and size.
dice_sum = dice1 + dice2
# We've got three separate 10x1 matrices. To produce a single
# 10x3 matrix, we'll concatenate them along dimension 1.
resulting_matrix = tf.concat(values=[dice1, dice2, dice_sum], axis=1)
print(resulting_matrix)

tf.Tensor(
[[ 5  5 10]
 [ 4  3  7]
 [ 5  3  8]
 [ 3  3  6]
 [ 1  4  5]
 [ 4  1  5]
 [ 5  1  6]
 [ 6  4 10]
 [ 3  3  6]
 [ 2  3  5]], shape=(10, 3), dtype=int32)


**Finding the indices of the largest and smallest element**

The signatures of the functions are as follows:

tf.argmax(input, axis=None, name=None, output_type=tf.int64 )

tf.argmin(input, axis=None, name=None, output_type=tf.int64 )

In [66]:
# 1-D tensor
t5 = tf.constant([2, 11, 5, 42, 7, 19, -6, -11, 29])
print(t5)


i = tf.argmax(input=t5)
print('index of max; ', i)
print('Max element: ',t5[i].numpy())


i = tf.argmin(input=t5,axis=0).numpy()
print('index of min: ', i)
print('Min element: ',t5[i].numpy())


t6 = tf.reshape(t5, [3,3])
print(t6)


i = tf.argmax(input=t6,axis=0).numpy() # max arg down rows
print('indices of max down rows; ', i)

i = tf.argmin(input=t6,axis=0).numpy() # min arg down rows
print('indices of min down rows ; ',i)
print(t6)

i = tf.argmax(input=t6,axis=1).numpy() # max arg across cols
print('indices of max across cols: ',i)

i = tf.argmin(input=t6,axis=1).numpy() # min arg across cols
print('indices of min across cols: ',i)


tf.Tensor([  2  11   5  42   7  19  -6 -11  29], shape=(9,), dtype=int32)
index of max;  tf.Tensor(3, shape=(), dtype=int64)
Max element:  42
index of min:  7
Min element:  -11
tf.Tensor(
[[  2  11   5]
 [ 42   7  19]
 [ -6 -11  29]], shape=(3, 3), dtype=int32)
indices of max down rows;  [1 0 2]
indices of min down rows ;  [2 2 0]
tf.Tensor(
[[  2  11   5]
 [ 42   7  19]
 [ -6 -11  29]], shape=(3, 3), dtype=int32)
indices of max across cols:  [1 0 2]
indices of min across cols:  [0 1 1]


In [67]:
variable = tf.Variable([[1,3,5,7],[11,13,17,19]])
checkpoint= tf.train.Checkpoint(var=variable)
save_path = checkpoint.save('./vars')
variable.assign([[0,0,0,0],[0,0,0,0]])
variable
checkpoint.restore(save_path)
print(variable)

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[ 1,  3,  5,  7],
       [11, 13, 17, 19]], dtype=int32)>


**Using tf.function**

tf.function is a function that will take a Python function and return a TensorFlow graph. The advantage of this is that graphs can apply optimizations and exploit parallelism in the Python function (func). tf.function is new to TensorFlow 2.

tf.function( func=None, input_signature=None, autograph=True, experimental_autograph_options=None )

In [68]:
def f1(x, y):
    return tf.reduce_mean(input_tensor=tf.multiply(x ** 2, 5) + y**2)

f2 = tf.function(f1)
x = tf.constant([4., -5.])
y = tf.constant([2., 3.])

# f1 and f2 return the same value, but f2 executes as a TensorFlow graph
assert f1(x,y).numpy() == f2(x,y).numpy()
#The assert passes, so there is no output

In [69]:
a = tf.random.normal(shape=(2,2))
b = tf.random.normal(shape=(2,2))

with tf.GradientTape() as tape:
    tape.watch(a)
    c = tf.sqrt(tf.square(a)+tf.square(b))
    dc_da = tape.gradient(c,a)
    print(dc_da)

tf.Tensor(
[[-0.469929    0.89920384]
 [-0.66446555 -0.7976701 ]], shape=(2, 2), dtype=float32)


In [70]:
a = tf.Variable(a)
with tf.GradientTape() as tape:
    c = tf.sqrt(tf.square(a)+tf.square(b))
    dc_da = tape.gradient(c,a)
    print(dc_da)

tf.Tensor(
[[-0.469929    0.89920384]
 [-0.66446555 -0.7976701 ]], shape=(2, 2), dtype=float32)


In [71]:
with tf.GradientTape() as outer_tape:
    with tf.GradientTape() as tape:
        c = tf.sqrt(tf.square(a)+tf.square(b))
        dc_da = tape.gradient(c,a)
    d2c_d2a = outer_tape.gradient(dc_da,a)
    print(d2c_d2a)

tf.Tensor(
[[0.4264985  0.6867533 ]
 [0.44663432 0.50159544]], shape=(2, 2), dtype=float32)
